### ISSUE TITLE
Installation Guide Request 🍪

### ISSUE THREAD

**Issue by DoubleDoubleX** [SkriptInsight/SkriptInsightKt#1]
Hi,
This isn't much of an issue, more than it is a request. Your project seems very cool and I would love to use it; but I do not understand how you get the code to a VSCode extension/linter. I do not know kolin, could you possibly do a guide with the required software and commands to build and run the application on VSCode? It seems like a very unique and never-done before project that I'd like to try, but I am not that knowledged.
Thanks.

**Comment by tarna** [comment]
yes please

**Comment by matias-io** [comment]
Agreed, would be helpful.

**Comment by NickAcPT** [comment]
Hello there, I am deeply sorry for missing this issue.

The images that you all have likely seen from this software were implemented in (the now archived) https://github.com/SkriptInsight/SkriptInsight project. It was an earlier implementation and was not very usable.

I will however keep this issue opened and focus some of my attention back into this project to make sure this is addressed properly so that it becomes usable.

**Comment by matias-io** [comment]
No worries, It's hard to find motivation for projects sometimes. I suppose the idea is that if you want more people to use the project, you should make a step-by-step guide on how to build and run this code. Most Skripters might not know how to do this, myself included. (We don't mind some bugs :) ). Thanks.

**Comment by NickAcPT** [comment]
> No worries, It's hard to find motivation for projects sometimes. I suppose the idea is that if you want more people to use the project, you should make a step-by-step guide on how to build and run this code. Most Skripters might not know how to do this, myself included. (We don't mind some bugs :) ). Thanks.

@Reimagining No worries there, this code is not usable yet, but it will be as easy as installing the VS Code extension

**Comment by HARXINE** [comment]
hey what for me does not work this extension please help me for me no auto suggest or fix tab and anything

**Comment by NickAcPT** [comment]
> hey what for me does not work this extension please help me for me no auto suggest or fix tab and anything

@HARXINE Advanced features on the SkriptInsight extension are not being worked on anymore at this point in time. Thus, the extension only provides basic syntax colouring. This is due to the lack of motivation and some technical issues when parsing Skript.
